name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: docker build -t mayurchadokar/backend-project:latest .
        working-directory: ./backend  # Adjust this if your Dockerfile is in a different location
        
      - name: Push to Docker Hub
        run: docker push mayurchadokar/backend-project:latest
          
      - name: Stop existing container
        run: |
          docker stop backend-project-container || true
          docker rm backend-project-container || true
        continue-on-error: true

      - name: Run container
        run: |
          docker pull mayurchadokar/backend-project:latest
          docker run -d \
            --name backend-project-container \
            -p 3000:3000 \
            mayurchadokar/backend-project:latest

      - name: Clean up
        run: docker image prune -f
        continue-on-error: true