name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mayurchadokar/backend-project:latest
          
      - name: Stop existing container
        run: |
          docker stop backend-project-container || true
          docker rm backend-project-container || true
        continue-on-error: true

      - name: Deploy to EC2
        run: |
          docker pull mayurchadokar/backend-project:latest
          docker run -d \
            --name backend-project-container \
            -p 3000:3000 \
            mayurchadokar/backend-project:latest

      - name: Clean up old images
        run: docker image prune -f
        continue-on-error: true