name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
   build: 
      runs-on: self-hosted
      steps: 
          -  name: Checkout source
             uses: actions/checkout@v3 
          -  name: Login to docker hub
             run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          -  name: Build and docker image
             run: docker build -t ${{ secrets.DOCKER_USERNAME }}/Backend .
          -  name: Push docker image 
             run: docker push ${{ secrets.DOCKER_USERNAME }}/Backend:latest
               
   deploy: 
        needs : build 
        runs-on : [aws-ec2]

        steps: 
          - name: Pull image from docker hub 
            run: docker pull ${{ secrets.DOCKER_USERNAME }}/Backend:latest
          - name: Delete old containet 
            run: docker rm -f Backend-container
          - name: Run docker container
            run: docker run -d -p 3000:3000 --name Backend-container ${{ secrets.DOCKER_USERNAME }}/Backend