name: Deploy to EC2

on:
  push:
    branches:
      - main  # Runs on push to the main branch

jobs:
  build: 
    runs-on: self-hosted
    steps: 
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker buildx build --push -t mayurchadokar/myapp:latest.

      - name: Push Docker image 
        run: docker push mayurchadokar/myapp:latest

  deploy: 
    needs: build 
    runs-on: aws-ec2  # Ensure this matches your EC2 runner label

    steps: 
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Pull image from Docker Hub 
        run: docker pull mayurchadokar/myapp:latest

      - name: Stop and remove old container (if running)
        run: |
          docker stop myapp-container || true
          docker rm myapp-project-container || true

      - name: Run Docker container
        run: docker run -d -p 3000:3000 --name myapp-container mayurchadokar/myapp:latest
